### ISSUE TITLE
Found a dead link in awesome-makerdao

### ISSUE THREAD

**Issue by aburban90** [makerdao/awesome-makerdao#42]
https://github.com/makerdao/awesome-makerdao

The first link of "Watch your Dai" section:

# Watch your Dai

- [**CDP Alert**](https://cdpalert.org/): Alerts on Dai Collateralized Debt Positions !!!THIS IS A DEAD LINK!!!

**Comment by aburban90** [comment]
@ghettodev  @Davidutro

**Comment by Davidutro** [comment]
You can make PRs to awesome MakerDAO instead of creating an issue

**Comment by Davidutro** [comment]
fixed

https://github.com/makerdao/awesome-makerdao/commit/5beae962d2a3170bf6801c58fd85808f1028511e
