### ISSUE TITLE
add hackathon projects subpage

### ISSUE THREAD

**Issue by scottrepreneur** [makerdao/awesome-makerdao#45]
having a list of the winners/bounty seekers from the hackathons could be cool

**Comment by Davidutro** [comment]
Although it would be cool to do this, unfortunately, it is near impossible to find old hackathon project lists, even winners. It will take a lot of time to do this, so it is not a high priority at the moment. Also, it will need to be maintained and added to with each hackathon.

I am open to see a PR with some former hackathon project winners, but for now, I will close this issue and say we are putting this task in the icebox.
