### ISSUE TITLE
Opera Crypto Wallet

### ISSUE THREAD

**Issue by spiolat** [makerdao/awesome-makerdao#90]
Hello team,

May I ask you to reference Opera Crypto Wallet to the list of referenced wallets please ?  

https://www.opera.com/crypto

Thank you

**Comment by spiolat** [comment]
Hello there, 

Any chance to handle it or update me please ?

BR

**Comment by Davidutro** [comment]
The repo is no longer actively updated. You can do a PR, and when we refresh the repo we can perhaps include the Opera wallet. But tbh probably not worth your time.

We are not planning to refresh this repo any time soon.
